[functions]
directory = "netlify/functions"
external_node_modules = ["express", "cors", "dotenv", "mongoose", "axios", "bcryptjs","cloudinary","cors", "dotenv", "fs", "jsonwebtoken", "multer", "nodemailer", "otp-generator", "twilio", "serverless-http"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true
